In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
preprocessed_data=pd.read_csv("df_preprocessed_new.csv")

In [3]:
preprocessed_data.head()

group_reason_1  group_reason_2  group_reason_3  group_reason_4  Month  \
0               0               0               0               1      7   
1               0               0               0               0      7   
2               0               0               0               1      7   
3               1               0               0               0      7   
4               0               0               0               1      7   

   Weekday  Transportation Expense  Distance to Work  Age  \
0        1                     289                36   33   
1        1                     118                13   50   
2        2                     179                51   38   
3        3                     279                 5   39   
4        3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

### Here, as we are going to do logistic Regression, we should have the binary Target.So, we classify the "Absenteesims Time in Hours "  into binary. For this we can classify as Abseenties time more than 3 as '1' and less than that as '0'.

In [4]:
target=np.where(preprocessed_data['Absenteeism Time in Hours']>3, 1 ,0)

In [5]:
preprocessed_data['Target'] = target

In [6]:
preprocessed_data

group_reason_1  group_reason_2  group_reason_3  group_reason_4  Month  \
0                 0               0               0               1      7   
1                 0               0               0               0      7   
2                 0               0               0               1      7   
3                 1               0               0               0      7   
4                 0               0               0               1      7   
..              ...             ...             ...             ...    ...   
695               1               0               0               0      5   
696               1               0               0               0      5   
697               1               0               0               0      5   
698               0               0               0               1      5   
699               0               0               0               1      5   

     Weekday  Transportation Expense  Distance to Work  Age  \
0          1                     289                36   33   
1          1                     118                13   50   
2          2                     179                51   38   
3          3                     279                 5   39   
4          3                     289                36   33   
..       ...                     ...               ...  ...   
695        2                     179                22   40   
696        2                     225                26   28   
697        3                     330                16   28   
698        3                     235                16   32   
699        3                     291                31   40   

     Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                    239.554               30          0         2     1   
1                    239.554               31          0         1     0   
2                    239.554               31          0         0     0   
3                    239.554               24          0         2     0   
4                    239.554               30          0         2     1   
..                       ...              ...        ...       ...   ...   
695                  237.656               22          1         2     0   
696                  237.656               24          0         1     2   
697                  237.656               25          1         0     0   
698                  237.656               25          1         0     0   
699                  237.656               25          0         1     1   

     Absenteeism Time in Hours  Target  
0                            4       1  
1                            0       0  
2                            2       0  
3                            4       1  
4                            2       0  
..                         ...     ...  
695                          8       1  
696                          3       0  
697                          8       1  
698                          2       0  
699                          2       0  

[700 rows x 16 columns]

### so, we have the target we drop the Absenteeism Time in Hour column

In [7]:
preprocessed_data=preprocessed_data.drop("Absenteeism Time in Hours",axis=1)

In [8]:
preprocessed_data

group_reason_1  group_reason_2  group_reason_3  group_reason_4  Month  \
0                 0               0               0               1      7   
1                 0               0               0               0      7   
2                 0               0               0               1      7   
3                 1               0               0               0      7   
4                 0               0               0               1      7   
..              ...             ...             ...             ...    ...   
695               1               0               0               0      5   
696               1               0               0               0      5   
697               1               0               0               0      5   
698               0               0               0               1      5   
699               0               0               0               1      5   

     Weekday  Transportation Expense  Distance to Work  Age  \
0          1                     289                36   33   
1          1                     118                13   50   
2          2                     179                51   38   
3          3                     279                 5   39   
4          3                     289                36   33   
..       ...                     ...               ...  ...   
695        2                     179                22   40   
696        2                     225                26   28   
697        3                     330                16   28   
698        3                     235                16   32   
699        3                     291                31   40   

     Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                    239.554               30          0         2     1   
1                    239.554               31          0         1     0   
2                    239.554               31          0         0     0   
3                    239.554               24          0         2     0   
4                    239.554               30          0         2     1   
..                       ...              ...        ...       ...   ...   
695                  237.656               22          1         2     0   
696                  237.656               24          0         1     2   
697                  237.656               25          1         0     0   
698                  237.656               25          1         0     0   
699                  237.656               25          0         1     1   

     Target  
0         1  
1         0  
2         0  
3         1  
4         0  
..      ...  
695       1  
696       0  
697       1  
698       0  
699       0  

[700 rows x 15 columns]

## While performing logistic regression , we need to have equal proportion of Targets, or 45-55 % or 60-40% is also not bad

In [9]:
df=preprocessed_data.copy()

In [10]:
df['Target'].sum()

319

In [11]:
df['Target'].sum() / len(df)

0.45571428571428574

so, we have 45 % data as Target '1' and rest of it as '0'. So, it is 45-55 proportion , so we can proceed with the Logistic regression model

## As in regression is a supervised learning method, we need to split the data into INPUTS and TARGET.

In [12]:
inputs=df.iloc[:,:-1]

In [13]:
target=df.loc[:,"Target"]

### So, before procedding to the model we need to Standarized our INPUTS for better performance and high accuracy of the model

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()
scaler.fit(inputs)

StandardScaler()

In [16]:
inputs_transformed=scaler.transform(inputs)

In [17]:
inputs_transformed

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

## Splitting data into trainning and testing

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(inputs_transformed,target, train_size=0.8, random_state=666)

## Now, Finally its time to perform the logistic regression

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
clf = LogisticRegression(random_state=0,solver='liblinear', C=10.0).fit(X_train, y_train)

In [22]:
clf.score(X_train, y_train)

0.7875

In [23]:
clf.predict(X_train)

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,

In [24]:
clf.coef_

array([[ 3.05995577,  0.47369108,  2.06616228,  2.22863301,  0.14764622,
        -0.08243092,  0.74659867, -0.0067016 , -0.20181001,  0.01492197,
         0.35715231, -0.07046514,  0.46282448, -0.33153101]])

In [25]:
from sklearn.metrics import classification_report, confusion_matrix

In [26]:
confusion_matrix(y_train, clf.predict(X_train))

array([[246,  59],
       [ 60, 195]], dtype=int64)

## Summary table

In [27]:
clf.coef_

array([[ 3.05995577,  0.47369108,  2.06616228,  2.22863301,  0.14764622,
        -0.08243092,  0.74659867, -0.0067016 , -0.20181001,  0.01492197,
         0.35715231, -0.07046514,  0.46282448, -0.33153101]])

In [28]:
clf.intercept_

array([-0.28906395])

In [29]:
feature_columns=inputs.columns

In [30]:
feature_columns

Index(['group_reason_1', 'group_reason_2', 'group_reason_3', 'group_reason_4',
       'Month', 'Weekday', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets'],
      dtype='object')

In [31]:
summary_stat=pd.DataFrame(columns=["Feature"],data=feature_columns)

In [32]:
summary_stat['values']=np.transpose(clf.coef_)

In [33]:
summary_stat

Feature    values
0            group_reason_1  3.059956
1            group_reason_2  0.473691
2            group_reason_3  2.066162
3            group_reason_4  2.228633
4                     Month  0.147646
5                   Weekday -0.082431
6    Transportation Expense  0.746599
7          Distance to Work -0.006702
8                       Age -0.201810
9   Daily Work Load Average  0.014922
10          Body Mass Index  0.357152
11                Education -0.070465
12                 Children  0.462824
13                     Pets -0.331531

In [34]:
summary_stat.loc[len(summary_stat)]=["Intercept",clf.intercept_[0]]

In [35]:
summary_stat

Feature    values
0            group_reason_1  3.059956
1            group_reason_2  0.473691
2            group_reason_3  2.066162
3            group_reason_4  2.228633
4                     Month  0.147646
5                   Weekday -0.082431
6    Transportation Expense  0.746599
7          Distance to Work -0.006702
8                       Age -0.201810
9   Daily Work Load Average  0.014922
10          Body Mass Index  0.357152
11                Education -0.070465
12                 Children  0.462824
13                     Pets -0.331531
14                Intercept -0.289064

In [36]:
summary_stat["Odds_ratio"]=np.exp(list(summary_stat['values']))

In [37]:
summary_stat=summary_stat.sort_values('values',ascending=False)

In [38]:
summary_stat

Feature    values  Odds_ratio
0            group_reason_1  3.059956   21.326614
3            group_reason_4  2.228633    9.287162
2            group_reason_3  2.066162    7.894468
6    Transportation Expense  0.746599    2.109812
1            group_reason_2  0.473691    1.605911
12                 Children  0.462824    1.588554
10          Body Mass Index  0.357152    1.429254
4                     Month  0.147646    1.159103
9   Daily Work Load Average  0.014922    1.015034
7          Distance to Work -0.006702    0.993321
11                Education -0.070465    0.931960
5                   Weekday -0.082431    0.920875
8                       Age -0.201810    0.817250
14                Intercept -0.289064    0.748964
13                     Pets -0.331531    0.717824